const list_Pizza = [

    {
        number:32,
        id: 36,
        title: "margherita",
        author: "mit Tomatensauce & Käse",
        price: 8.5,
        img: "https://static.toiimg.com/thumb/56868564.cms?imgsize=1948751&width=800&height=800",
        amount: 1,    
    }, 
    {
        number:33,
        id: 37,
        title: "salami",
        author: "mit Rinder-Salami",
        price: 9.5,
        img: "https://meliz-palast.de/wp-content/uploads/2017/02/2017-01-19_Meliz_0065.jpg",
        amount: 1,    
    }, 

    {
        number:34,
        id: 38,
        title: "schinken",
        author: "mit Puten-Formfleischschinken",
        price: 9.5,
        img: "https://www.italienische-rezepte.net/wp-content/uploads/2021/01/pizza-schinken.jpg",
        amount: 1,    
    }, 
    {
        number:35,
        id: 39,
        title: "Tonno",
        author: "mit Thunfisch,Zwiebeln",
        price: 10,
        img: "https://www.lieferando.de/foodwiki/uploads/sites/8/2019/04/pizza-tonno-1080x1080.jpg",
        amount: 1,    
    }, 
    {
        number:36,
        id: 40,
        title: "Funghi",
        author: "mit frischen Pilzen",
        price: 9.5,
        img: "https://www.lieferando.de/foodwiki/uploads/sites/8/2019/04/pizza-funghi-1080x1080.jpg",
        amount: 1,    
    }, 
    {
        number:37,
        id: 41,
        title: "Hawaii",
        author: "mit Puten-Formfleischschinken, Ananas",
        price: 10,
        img: "https://www.lieferando.de/foodwiki/uploads/sites/8/2019/04/pizza-hawaii-1080x1080.jpg",
        amount: 1,    
    }, 
    {
        number:38,
        id: 42,
        title: "Vegetarisch",
        author: "mit Paprika , frischen Pilzen, Oliven, Mais, Brokkoli,Zwiebeln",
        price: 10,
        img: "https://www.hobbybaecker.de/recipes/image/QrX876rFyetirOd1CkEFxf6Fq6H7QS0d.jpg",
        amount: 1,    
    }, 
    {
        number:39,
        id: 43,
        title: "Pizza Uni ",
        author: "mit puten-Formfleischschinken, frischen Pilzen, Rinder-Salami, Ei",
        price: 11,
        img: "",
        amount: 1,    
    }, 
    {
        number:40,
        id: 44,
        title: "Sucuk",
        author: "mit Knoblauchwurst & Käse",
        price: 11,
        img: "https://frenks.de/cdn/shop/products/PizzaSucuk_1024x1024.jpg?v=1591626835",
        amount: 1,    
    }, 
    {
        number:41,
        id: 45,
        title: "Pizza Kebap",
        author: "mit Kebapfleisch o. Chickendöner, und Zwiebeln",
        price: 11,
        img: "https://media-cdn.tripadvisor.com/media/photo-s/17/be/58/3c/photo2jpg.jpg",
        amount: 1,    
    }, 
    {
        number:42,
        id: 46,
        title: "Mista",
        author: "mit Pilzen, Rinder-Salami, Peperoni",
        price: 11,
        img: "https://www.lieferando.de/foodwiki/uploads/sites/8/2019/04/pizza-mista-2-1080x1080.jpg",
        amount: 1,    
    }, 
    {
        number:43,
        id: 46,
        title: "Pizza Calzona",
        author: "mit Kebapfleisch o. Chickendöner, und Zwiebeln",
        price: 11,
        img: "https://media-cdn.tripadvisor.com/media/photo-s/0e/a5/a2/2f/calzona.jpg",
        amount: 1,    
    }, 



];
  
  export default list_Pizza;