const list_vergelarisches = [ 

    {
        number:60,
        id: 64,
        title: " Halloumi ",
        price: 7,
        author: "im Fladenbrot mit Salat & Soße",
        img: "https://feelgoodfoodie.net/wp-content/uploads/2020/07/Grilled-Halloumi-4.jpg",
        amount: 1,    
    },
    {
        number:'60a',
        id: 65,
        title: " Halloumi ",
        price: 4.5,
        author: "im Fladenbrot mit  Soße",
        img: "https://feelgoodfoodie.net/wp-content/uploads/2020/07/Grilled-Halloumi-4.jpg",
        amount: 1,    
    },
    {
        number:61,
        id: 66,
        title: " Halloumi Teller ",
        price: 9,
        author: "im Pommes, Salat & Soße",
        img: "https://feelgoodfoodie.net/wp-content/uploads/2020/07/Grilled-Halloumi-4.jpg",
        amount: 1,    
    },
    {
        number:62,
        id: 66,
        title: " Falafel",
        price: 7,
        author: " 3 Stk. im Fladenbrot mit Salat & Soße",
        img: "https://tastythriftytimely.com/wp-content/uploads/2023/06/Falafel-Pita-FEATURED.jpg",
        amount: 1,    
    },
    {
        number:63,
        id: 67,
        title: " Falafel Teller ",
        price: 9,
        author: " 6 Stk. im Fladenbrot mit Salat & Soße",
        img: "https://tastythriftytimely.com/wp-content/uploads/2023/06/Falafel-Pita-FEATURED.jpg",
        amount: 1,    
    },
    {
        number:64,
        id: 68,
        title: " Vegetarisch  ",
        price: 6,
        author: " im Fladenbrot mit Salat & Soße",
        img: "https://i.redd.it/w3rslxycjaiz.jpg",
        amount: 1,    
    },
    {
        number:65,
        id: 69,
        title: " Vegetarisch Spezial ",
        price: 6.5,
        author: " im Fladenbrot mit Weißkäse, Salat & Soße",
        img: "https://i.redd.it/w3rslxycjaiz.jpg",
        amount: 1,    
    },
    {
        number:66,
        id: 70,
        title: " Vegetarisch Teller ",
        price: 9.5,
        author: " 4 Falafel , 1 Scheiben Halloumi, Pommes, Salat ",
        img: "https://leckerabnehmen.com/wp-content/uploads/2022/07/Low-Carb-Doener-Teller-mit-Salat.webp",
        amount: 1,    
    },
    {
        number:67,
        id: 71,
        title: " Vegetarisch Dürüm ",
        price: 7.5,
        author: " 4 Falafel , 1 Scheiben Halloumi dazu Salat & Soße ",
        img: "https://www.marions-kochbuch.de/rezept/5697.jpg",
        amount: 1,    
    },
    {
        number:68,
        id: 72,
        title: "Pommes",
        price: 4,
        author: " Klein ",
        img: "https://www.gutekueche.at/storage/media/recipe/101829/conv/perfekte-pommes-frites-default.jpg",
        amount: 1,    
    },
    {
        number:69,
        id: 73,
        title: "Pommes",
        price: 5.5,
        author: " Größ ",
        img: "https://img1.kochrezepte.at/use/0/selbstgemachte-pommes-frites_963.jpg",
        amount: 1,    
    },
];

export default list_vergelarisches;